import { Container } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<Container bg={'blackAlpha.600'}>
			<Head>
				<title>TrendRoad </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</Container>
	)
}

export default Home
